### PR TITLE
Initialize logger with prom config from flags

### PR DESCRIPTION
**Pull request by brennantaylor**
It looks like the logger is initialized with an empty config, then a different
config is passed into kingpin to be filled up from the command line arguments.

This change re-initializes the logger with the prom config parsed by kingpin so
that `--log.level` and `--log.format` work as documented.

### CODE REVIEW

**Comment by n-oden** [comment]
@brennantaylor thank you so much; this one was driving me somewhat nuts and I couldn't figure out where the breakage was.

**Comment by pengbo0328** [comment]
@brennantaylor 
It seems your patch doesn't fix this issue. Did I miss any configurations?

```
./pgpool2_exporter --log.level=error
ts=2022-01-17T08:06:13.818Z caller=log.go:168 level=debug msg="Querying namespace" namespace=pool_processes
ts=2022-01-17T08:06:13.821Z caller=log.go:168 level=debug msg="Querying namespace" namespace=pool_cache
ts=2022-01-17T08:06:13.821Z caller=log.go:168 level=debug msg="Querying namespace" namespace=pool_nodes
ts=2022-01-17T08:06:13.842Z caller=log.go:168 level=debug msg="Querying Pgpool-II version"
ts=2022-01-17T08:06:13.844Z caller=log.go:168 level=debug pgpool_version=4.3.0
ts=2022-01-17T08:06:13.844Z caller=log.go:168 level=info msg="Starting pgpool2_exporter" version="(version=, branch=, revision=)" dsn="postgresql://pengbo:MASKED_PASSWORD@127.0.0.1:11000/test?sslmode=disable"
ts=2022-01-17T08:06:13.844Z caller=log.go:168 level=info msg="Listening on address" address=:9719
```

**Comment by brennantaylor** [comment]
Interesting I was just testing json. I'll take a peek at the log levels.

Without my patch:
```
dbox:~/ghq/github.com/brennantaylor/pgpool2_exporter$ go run . --log.format=json
ts=2022-01-18T04:16:10.766Z caller=log.go:168 level=error err="error connecting to Pgpool-II: dial tcp [::1]:5432: connect: connection refused"
```

With my patch json formatting turns on.
```
 go run . --log.format=json 2>&1 | jq
{
  "caller": "log.go:168",
  "err": "error connecting to Pgpool-II: dial tcp [::1]:5432: connect: connection refused",
  "level": "error",
  "ts": "2022-01-18T04:17:33.769Z"
}
```

**Comment by brennantaylor** [comment]
I poked around a bit but found nothing obvious. The `--log.level` param is being read and it sets the field on the config properly. It is then passed into new which creates a `NewFilter`. But indeed log messages don't seem to respect the level.

**Comment by brennantaylor** [comment]
Oh I think I figured it out. There is `github.com/go-kit/kit/log/level` which promlog is using and `github.com/go-kit/log/level` which `pgpool2_exporter` is using.

I believe `go-kit/log` exists in case someone wants to use the logging code without pulling in the rest of `go-kit` but that means we're cross wiring logger instances.

So just a library mixup. I'll try changing `pgpool2_exporter` to use the same library promlog is using.

**Comment by brennantaylor** [comment]
@pengbo0328 I pushed the changes, you should see that both `--log.level` and `--log.format` work.

**Comment by brennantaylor** [comment]
@pengbo0328 Just letting you know this is ready for you to take another look at.

**Comment by pengbo0328** [comment]
@brennantaylor 
Thank you!
I have tested your patch and it fixes the logger problems.

**Pull request merged**
