### PR TITLE
Break off main function to make module importable

### PR DESCRIPTION
**Pull request by n-oden**
Also update reqs to go 1.17 and apply gofmt.

This should resolve https://github.com/pgpool/pgpool2_exporter/issues/4

### CODE REVIEW

**Comment by n-oden** [comment]
Hey @pengbo0328 any thoughts on this and #11 ?

**Comment by n-oden** [comment]
@pengbo0328 I've taken another pass at this.  The instructions in the README should still be correct: `make` should create the binary in the top of the repo.

**Comment by pengbo0328** [comment]
@n-oden Thank you! It works and the the binary is created in the top of the repo now.
Do you think we should rename file `cmd/pgpool2_exporter/pgpool2_exporter.go` to other name?

**Comment by n-oden** [comment]
@pengbo0328 good idea -- all done now!

**Comment by pengbo0328** [comment]
@n-oden Thank you!

**Pull request merged**
